<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to partial and module testing app %s:)%s'), '<span class="zf-green">', '</span>') ?></h1>    
</div>

<div class="row" style="margin: 10px;">
    <?php if($chart_form): ?><a id="chart2_draw" href="<?php echo $this->url('chart2', array('action'=>'draw'));?>"><?= $this->translate('Click to draw a new chart') ?></a><?php endif; ?>
</div>

<div class="row" style="margin: 10px;">
    <?php echo $this->translate('Everything above (including the layout) comes from the "Application" module') ?>
</div>

<div class="row" style="margin: 10px;">
    <?php if($chart_form) echo $this->partial('cp.phtml', array('chart_form'=>$chart_form)); ?>
</div>

<div id="chart2_area"></div>

<div class="row" style="margin: 10px;">
    <?php echo $this->translate('The footer comes from the "Application" module') ?>
</div>